//    Openbravo POS is a point of sales application designed for touch screens.
//    Copyright (C) 2007-2009 Openbravo, S.L.
//    http://www.openbravo.com/product/pos
//
//    This file is part of Openbravo POS.
//
//    Openbravo POS is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    Openbravo POS is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with Openbravo POS.  If not, see <http://www.gnu.org/licenses/>.

package com.openbravo.pos.reports;

import com.openbravo.basic.BasicException;
import com.openbravo.data.loader.Datas;
import com.openbravo.data.loader.QBFCompareEnum;
import com.openbravo.data.loader.SerializerWrite;
import com.openbravo.data.loader.SerializerWriteBasic;
import com.openbravo.format.Formats;
import com.openbravo.pos.forms.AppLocal;
import com.openbravo.pos.forms.AppView;
import java.awt.Component;

/**
 *
 * @author  adrianromero
 */
public class JParamsComboCompany extends javax.swing.JPanel implements ReportEditorCreator {
    
    private Datas datasvalue;
    private Formats formatsvalue;
    private QBFCompareEnum comparevalue;
    
    /** Creates new form JParamsText */
    public JParamsComboCompany() {
        initComponents();
        
        setLabel(AppLocal.getIntString("label.value"));
        setType(Formats.STRING);
    }
    
    public JParamsComboCompany(String label) {
        
        initComponents();
        
        setLabel(label);    
        setType(Formats.STRING);
    }
    
    public JParamsComboCompany(String label, Formats format) {
        
        initComponents();
        
        setLabel(label);    
        setType(format);
    }
    
    public JParamsComboCompany(String label, Formats format, Datas data) {
        
        initComponents();
        
        setLabel(label);    
        setType(format, data);
    }
    
    public void setLabel(String label) {
        lblField.setText(label);
    }
    
    public void setType(Formats format, Datas data) {
        formatsvalue = format;
        datasvalue = data;
        setDefaultCompare();
    }
    
    public void setType(Formats format) {
        
            setType(format, Datas.STRING);
        
    }
    
    public void setCompare(QBFCompareEnum compare) {
        comparevalue = compare;
    }
    
    private void setDefaultCompare() {
        
             comparevalue = QBFCompareEnum.COMP_RE;
        
    }
    
    public void init(AppView app) {
    }

    public void activate() throws BasicException {
        jComboBox1.setSelectedIndex(0);
    }
    
    public SerializerWrite getSerializerWrite() {
        return new SerializerWriteBasic(new Datas[] {Datas.OBJECT, datasvalue});
    }

    public Component getComponent() {
        return this;
    }
    
    public Object createValue() throws BasicException {
        
        Object value = formatsvalue.parseValue(jComboBox1.getSelectedItem().toString());
        //txtField.setText(formatsvalue.formatValue(value));
        
        if (value == null||value.equals("TODAS")) {        
            return new Object[] {QBFCompareEnum.COMP_NONE, null};
        } else {
            return new Object[] {comparevalue, value};
        }
    }      
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblField = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(0, 30));
        setLayout(null);

        lblField.setText("***");
        add(lblField);
        lblField.setBounds(20, 10, 120, 14);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODAS", "BAJIOQ SERVICIOS TECNICOS COREY, S.A. C.V.", "MEX SERVICIOS INTEGRALES COREY, S.A.CV", "MEX SERVICIOS TECNICOS COREY SA DE CV", "STO INDUSTRIAS RECAL SA DE CV", "STO SERVICIOS INTEGRALES COREY, S.A. DE C.V.", "STOQ SERVICIOS TECNICOS COREY, S.A. C.V.", "STOS LOGISTICA CORCAL, SA DE CV", "STOS SERVICIOS TECNICOS COREY, S.A. DE C.V." }));
        add(jComboBox1);
        jComboBox1.setBounds(140, 10, 300, 20);
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel lblField;
    // End of variables declaration//GEN-END:variables
    
}
